version: '3.8'

services:
  backend:
    build: ./node/
    ports:
      - 3000:3000
  loadbalancer:
    image: nginx
    ports: 
      - 8080:80
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27017:27017
    volumes:
      - db_data:/data/db
  mongoexpress:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
volumes:
  db_data:
